### PR TITLE
Changes for logging, database connection and IAM email.

### PR DESCRIPTION
**Pull request by adamdyson**
Allow the database host and name to be defined by end-users. You should not assume that the database is hosted locally or force a particular database name.

End-users should be able to specify where log files are generated. Files should never be created or changed within a package directory. Otherwise Composer will flag this as a problem.

Please see the changes to the `ZohoOAuthClient::getUserEmailIdFromIAM()` method. I'm interested to hear your opinion on this.

### CODE REVIEW

**Comment by blacknell** [comment]
Relates #28

**Comment by tristanbes** [comment]
Bump ?¿

**Comment by tristanbes** [comment]
Hello, without this PR it spams our error analysis system with 
`ErrorException: fwrite() expects parameter 1 to be resource, boolean given`
`ErrorException: fclose() expects parameter 1 to be resource, boolean given`

Can you please merge this ?

**Comment by tristanbes** [comment]
Hello @sumanthchilka, do you care to look at this patch please ? 

We are paying Zoho customers who want to use this library that doesn't SPAM our repporting tools with fake issues due to unclosed problem on 3rd party code please....

**Comment by pravesh-a** [comment]
features will be supported in the upcoming SDK versions

**Comment by tristanbes** [comment]
.... when will it happen @pravesh-a ?

**Pull request closed without merging**
