### PR TITLE
fixed case of filename TagAPIHandler.php & oauth logfile permission denied

### PR DESCRIPTION
**Pull request by blacknell**
1. On case insensitive systems (MacOS) this isn't a problem but where the filesystem is case sensitive then the API fails since this call fails in src/com/zoho/crm/library/crud/ZCRMModule.php

`realpath(dirname(__FILE__).'/../api/handler/TagAPIHandler.php')`

2. PHPUnit tests fail when permission is denied on oauth logfile & app logfile

### CODE REVIEW

**Comment by blacknell** [comment]
I don't think your library should be writing to files in the library hierarchy as is done with the oauth logger. not many admins would permit this in a production set up.
I think you should consider allowing [passing a monolog/monolog logger](https://github.com/Seldaek/monolog) object (both for the oauth logger and the app logger) so the library user can control this

**Comment by blacknell** [comment]
partially fixed in [1.15](https://github.com/zoho/zcrm-php-sdk/commit/ed6e73dc5117aa30fd54faa90bb41e116d746031)

**Comment by blacknell** [comment]
hi @sumanthchilka 
what's happening about the logfile problems being addressed?

**Comment by blacknell** [comment]
Relates #20

**Comment by blacknell** [comment]
Nothing seems to happen and never a response. I also contacted Zoho via support

**Comment by pravesh-a** [comment]
fixed in SDK.

**Pull request closed without merging**
