### PR TITLE
Conversion / Refactor  (Please consider)

### PR DESCRIPTION
**Pull request by dylanlawrence**
The current state of this project is a blocker for us ( at least to proceed with ) - Our `vendor` code is created during the ( build / profiling) process and should **not** contain configuration code.

I spent some time modernizing the code, mostly syntactical with the same logic - other than the config being replaced by a _**config.yml**_ file.  
The unit tests were not converted, but left in place since they should still be very close and probably only need changes to includes.

Although I believe this code still works as intended, I realize that 138 files is not exactly a PR.

Please review my [fork](https://github.com/dylanlawrence/zcrm-php-sdk) or [package](https://packagist.org/packages/dylanlawrence/zohocrm)  

`composer require dylanlawrence/zohocrm dev-master`

### CODE REVIEW

**Comment by ralphschindler** [comment]
I have to concur with @dylanlawrence, there are major blockers in this library in addition to it being not very modern with regards to php library standards.  Please consider a formal refactor and at least address some of these points:

* use PSR2 coding style
* use PSR4 autoloading conventions (with composer support), ie: don't `require_once`
* use some form of common HTTP client abstraction
* don't touch the `include_path`; ie: `set_include_path`
* use psr3 for logging (the typical logger being monolog)

Good luck!
-ralph

**Comment by evgeny-barinov** [comment]
Really necessary changes. Please accept the pull request ASAP. Especially for config files reading. Now much more convenient to use the fork instead of official SDK. Thanks!

**Comment by plamenst** [comment]
Please review the changes in this PR (and the others) and consider refactoring. Currently the code quality is very low!
Also when there are no records found (for example when perform search) exception is thrown, maybe will be better to return an empty APIResponse or something similar.

**Comment by pravesh-a** [comment]
refactoring and cleanup will be done in the upcoming versions of the SDK.

**Pull request closed without merging**
